ALTER TABLE TB_USUARIO DROP FOREIGN KEY FK_TB_USUARIO_ID_CARTAO_CREDITO
ALTER TABLE TB_TELEFONE DROP FOREIGN KEY FK_TB_TELEFONE_ID_USUARIO
DROP TABLE TB_CARTAO_CREDITO
DROP TABLE TB_USUARIO
DROP TABLE TB_TELEFONE

